### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rajatgoyal715**
Create Contributing file
	
# Related Issue	
#10 

# Changes Proposed	
Add new Contributing file

### CODE REVIEW

**Review by rajat19 — COMMENTED** [review]
I had updated the md file

**Comment by rajat19** [comment]
@rajatgoyal715  please approve changes

**Comment by rajatgoyal715** [comment]
@rajat19 Please see the preview of the file as it is not rendering how it is intended.

**Comment by rajat19** [comment]
# Contributing

Contributions are welcome, and they are greatly appreciated! Every
little bit helps, and credit will always be given.

You can contribute in many ways:

Types of Contributions
----------------------

Report Bugs
~~~~~~~~~~~

Report bugs on the `issues page`_. If you are reporting a bug, please include:

* Any details about your local setup that might be helpful in troubleshooting.
* Detailed steps to reproduce the bug.

Fix Bugs
~~~~~~~~

Look through the GitHub issues for bugs. Anything tagged with "bug"
is open to whoever wants to implement it.

Implement Features
~~~~~~~~~~~~~~~~~~

Look through the GitHub issues for features. Anything tagged with "feature"
is open to whoever wants to implement it.

Write Documentation
~~~~~~~~~~~~~~~~~~~

This module could always use more documentation, whether as part of the
official docs, in docstrings, or other.

Submit Feedback
~~~~~~~~~~~~~~~

The best way to send feedback is to file an ticket on the `issues page`_. If you
are proposing a feature:

* Explain how it would work.
* Keep the scope as narrow as possible, to make it easier to implement.
* Remember that this is a volunteer-driven project, and that contributions
  are welcome :)

Get Started!
------------

Ready to contribute? Here's how to set up `Hackerrank-Solution-Crawler` for local development.

1. Fork the `Hackerrank-Solution-Crawler` repo on GitHub.
2. Clone your fork locally::

    $ git clone git@github.com:Nullifiers/Hackerrank-Solution-Crawler.git

3. Create a branch for local development::

    $ git checkout -b name-of-your-bugfix-or-feature

   Now you can make your changes locally.

4. Commit your changes, quoting github issue in the commit message, if applicable
   and push your branch to GitHub::

    $ git add .
    $ git commit -m "Fix #XX - My awesome fix"
    $ git push origin name-of-your-bugfix-or-feature

5. Submit a pull request through the GitHub website.

**Comment by rajat19** [comment]
Please comment the intended preview

**Comment by rajat19** [comment]
Ok i got it

**Comment by rajat19** [comment]
@rajatgoyal715  please check now

**Pull request merged**
